### ISSUE TITLE
这位老铁为何如此优秀!

### ISSUE THREAD

**Issue by gm100861** [xiongwilee/recipes#3]
程序员找女朋友的时间都没有,你哪来的时间做菜.同样是程序员,为何你这么优秀.
老铁有没有录制教学视频的计划,新手,有些做菜名词看不太懂.想学.

**Comment by xiongwilee** [comment]
- https://weibo.com/u/6288254740
- https://weibo.com/u/6331792123

现在的年轻程序员啊就是太浮躁！拿去慢慢学！早点找到女朋友！
